-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.4.2
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
        args: [--exclude=kolibri/*/migrations/*]
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: end-of-file-fixer

-   repo: git://github.com/pre-commit/mirrors-jshint
    sha: v2.8.0
    hooks:
    -   id: jshint
