# Config file for automatic testing at travis-ci.org

language: python

services:
  - postgresql

sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/pip
    - travis_phantomjs

matrix:
  include:
    - python: "2.7"
      env:
        - TOX_ENV=pythonbuild2.7
        - TRAVIS_NODE_VERSION="4"
    - python: "3.4"
      env:
        - TOX_ENV=pythonbuild3.4
        - TRAVIS_NODE_VERSION="4"
    - python: "3.5"
      env:
        - TOX_ENV=pythonbuild3.5
        - TRAVIS_NODE_VERSION="4"
    - python: "2.7"
      env:
        - TOX_ENV=pythonlint
        - TRAVIS_NODE_VERSION="4"
    - python: "2.7"
      env:
        - TOX_ENV=licenses
        - TRAVIS_NODE_VERSION="4"
    - python: "2.7"
      env:
        - TOX_ENV=py2.7
        - TRAVIS_NODE_VERSION="4"
    - python: "2.7"
      env:
        - TOX_ENV=docs
        - TRAVIS_NODE_VERSION="4"
    - python: "2.7"
      env:
        - TOX_ENV=bdd
        - TRAVIS_NODE_VERSION="4"
    - python: "3.4"
      env:
        - TOX_ENV=py3.4
        - TRAVIS_NODE_VERSION="4"
    - python: "3.5"
      env:
        - TOX_ENV=py3.5
        - TRAVIS_NODE_VERSION="4"
    - python: "2.7"
      env:
        - TOX_ENV=node4.x
        - TRAVIS_NODE_VERSION="4"
    - python: "2.7"
      env:
        - TOX_ENV=node5.x
        - TRAVIS_NODE_VERSION="5"
    - python: "2.7"
      env:
        - TOX_ENV=postgres
        - TRAVIS_NODE_VERSION="4"
    - python: "2.7"
      env:
        - TOX_ENV=npmbuild
        - TRAVIS_NODE_VERSION="4"

before_install:
  - pip install -U pip
  - pip install codecov
  - pip install tox
  - . $HOME/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
# install PhantomJS 2
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "phantomjs --version"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "export PHANTOMJS_BIN=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs"
  - "phantomjs --version"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to run tests, e.g. python setup.py test
script:
  - tox -e $TOX_ENV

after_success:
  - codecov

notifications:
  slack:
    secure: RH3xqTkkoA2TATYo7onoLlAlw5t7Bek3HqN/e48e1mj3nazTUs05k12e9Cj7I/y7rBu4b1g0Fl4nJ/DOJRD/81o2ML8OAqu4Ngfg149EQysvgHki20CY1LMph0aS5HSACL1yvp8VvDmmpF0F8YGh99ZMeV3qdp0t3AVWSQVIQgVOEjUSPklsf25ikCOqzTRCz90Dp5aIlDUuXtubTATaKQiLfqW8rc/S7Q/JLepmZau5ANFz8cHXn750y6EvEREIE/0gBwH6OWOa1qWCavJPc4z9953zX7rhI85f0eaHVYQ0ojeXJjQG4MOu5kP13tkaLppe1On3fBZLPpeF791EJwgcmEFUd8hDsomfHcxXhHf7+LPwbGjelGr8iY/2ZIWuILY17FmnWyruWyusrHpA1YKBFwjqgo7E06uzwVj9npxbc+WEHuBxTDdaeFYjYRLORvOeJ9y3n+rNs2c9gCvwuq3MzhMWT+KsrrngAibns1Fz/I1YZAY3voipmabeXVLqbLvb8f8xBmwwK14ba0tGMHfnnCfivlruS49qLwpMjASEPY3H8lKyROX94aaWj+B1Fld2kX0L5GN3xkVoT1aJOgOxCF9c7w9Kf1aTcf/T4bfEzjPNf3ZH3rwy/b3YABbQAEdV8SLdrD02+CIYNPzv3/U1y3rmTSg0wLT2elumhv8=
