# Config file for automatic testing at travis-ci.org

language: python

sudo: false

cache:
  directories:
    - node_modules

matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=py2.7
    - python: "2.7"
      env: TOX_ENV=docs
    - python: "2.7"
      env: TOX_ENV=bdd
    - python: "3.4"
      env: TOX_ENV=py3.4
    - python: "3.5"
      env: TOX_ENV=py3.5

before_install:
  - pip install codecov
  - pip install tox

install:
  - npm install

before_script:
  - tox -e lint

# command to run tests, e.g. python setup.py test
script:
  - tox -e $TOX_ENV
  - npm run coverage

after_success:
  - codecov
