name: Docs

on:
  push:
  pull_request:
    paths:
      - 'docs/**'
      - 'requirements/docs.txt'

jobs:
  docs:
    name: Checking docs build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-docs-${{ hashFiles('requirements/docs.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-docs
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/docs.txt
    - name: Check Docs build
      run: make docs
